### ISSUE TITLE
How to generate GENESIS_TX and GENESIS_NONCE?

### ISSUE THREAD

**Issue by 15963** [inbestcoin/How-to-create-your-own-cryptocurrency#1]
How to generate GENESIS_TX and GENESIS_NONCE?

demo:
std::string const GENESIS_TX = "013c01ff0001ffffffffffff0302df5d56da0c7d643ddd1ce61901c7bdc5fb1738bfe39fbe69c28a3a7032729c0f2101168d0c4ca86fb55a4cf6a36d31431be1c53a3bd7411bb24e8832410289fa6f3b";
uint32_t const GENESIS_NONCE = 10002;

thank you for any help!!!

**Comment by luiscosio** [comment]
Hello!

You need to follow these steps:

7. ./simplewallet --config-file configs/fakecoin.conf --generate-new-wallet genesis.wallet --password 12345
8. Copy new wallet address (For example, FSgLDzpszX3S3RMK5p8PfCeY1eqchFSZsf5LcgPsA4EcJ6wpXrKGr7AViBqLATZ9K6CqQPgR8opQq6zY2HTCsVuWEANv6pq)
9. ./forknoted --config-file configs/fakecoin.conf --print-genesis-tx --genesis-block-reward-address FSgLDzpszX3S3RMK5p8PfCeY1eqchFSZsf5LcgPsA4EcJ6wpXrKGr7AViBqLATZ9K6CqQPgR8opQq6zY2HTCsVuWEANv6pq
10. Copy genesis block and add it to configs/fakecoin.conf, it should be without spaces or new lines, if there is a space in the genesis block you did something wrong (For example, GENESIS_COINBASE_TX_HEX=010a01ff0001e4e7cc99b3e6cc993302ebc5f7d91fcfd005a97c9edfa06caf50025b816603a59c60f5341c167a59df2b21015679abce2289c95178a76d111faaadacb3f71584555f395b16804819880085df)

**Comment by 15963** [comment]
@luiscosio ok! I try later,thank you!
